/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "gxovnt.messaging.config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gxovnt_messaging_Configuration, gxovnt_messaging_Configuration, AUTO)


PB_BIND(gxovnt_messaging_Configuration_SystemSettings, gxovnt_messaging_Configuration_SystemSettings, AUTO)


PB_BIND(gxovnt_messaging_Configuration_WiFiSettings, gxovnt_messaging_Configuration_WiFiSettings, AUTO)


PB_BIND(gxovnt_messaging_Configuration_BLETPMS, gxovnt_messaging_Configuration_BLETPMS, AUTO)



