/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "messages/gxovnt_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GXOVnTConfig, GXOVnTConfig, AUTO)


PB_BIND(GXOVnTConfig_SYSTEM_SETTINGS, GXOVnTConfig_SYSTEM_SETTINGS, AUTO)


PB_BIND(GXOVnTConfig_WIFISETTINGS, GXOVnTConfig_WIFISETTINGS, AUTO)


PB_BIND(GXOVnTConfig_BLE_TPMS, GXOVnTConfig_BLE_TPMS, AUTO)



