/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "messages/msg_gxovnt_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MSG_GXOVnT_Config, MSG_GXOVnT_Config, AUTO)


PB_BIND(MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings, MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings, AUTO)


PB_BIND(MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings, MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings, AUTO)


PB_BIND(MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS, MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS, AUTO)



