// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gxovnt.messaging.container.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gxovnt.Messaging {

  /// <summary>Holder for reflection information generated from gxovnt.messaging.container.proto</summary>
  public static partial class GxovntMessagingContainerReflection {

    #region Descriptor
    /// <summary>File descriptor for gxovnt.messaging.container.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GxovntMessagingContainerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBneG92bnQubWVzc2FnaW5nLmNvbnRhaW5lci5wcm90bxIQZ3hvdm50Lm1l",
            "c3NhZ2luZxoeZ3hvdm50Lm1lc3NhZ2luZy5jb21tYW5kLnByb3RvGh1neG92",
            "bnQubWVzc2FnaW5nLmNvbmZpZy5wcm90byLuAQoJQ29udGFpbmVyEkEKDW1l",
            "c3NhZ2VUeXBlSWQYASABKA4yKi5neG92bnQubWVzc2FnaW5nLkNvbnRhaW5l",
            "ci5NZXNzYWdlVHlwZV9JZBIsCgdDb21tYW5kGAIgASgLMhkuZ3hvdm50Lm1l",
            "c3NhZ2luZy5Db21tYW5kSAASMQoGQ29uZmlnGAMgASgLMh8uZ3hvdm50Lm1l",
            "c3NhZ2luZy5Db25maWd1cmF0aW9uSAAiNgoOTWVzc2FnZVR5cGVfSWQSCwoH",
            "Q09NTUFORBAAEgoKBkNPTkZJRxABEgsKB1Vua25vd24QY0IFCgNtc2diBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gxovnt.Messaging.GxovntMessagingCommandReflection.Descriptor, global::Gxovnt.Messaging.GxovntMessagingConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gxovnt.Messaging.Container), global::Gxovnt.Messaging.Container.Parser, new[]{ "MessageTypeId", "Command", "Config" }, new[]{ "Msg" }, new[]{ typeof(global::Gxovnt.Messaging.Container.Types.MessageType_Id) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Container : pb::IMessage<Container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Container> _parser = new pb::MessageParser<Container>(() => new Container());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gxovnt.Messaging.GxovntMessagingContainerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container(Container other) : this() {
      messageTypeId_ = other.messageTypeId_;
      switch (other.MsgCase) {
        case MsgOneofCase.Command:
          Command = other.Command.Clone();
          break;
        case MsgOneofCase.Config:
          Config = other.Config.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container Clone() {
      return new Container(this);
    }

    /// <summary>Field number for the "messageTypeId" field.</summary>
    public const int MessageTypeIdFieldNumber = 1;
    private global::Gxovnt.Messaging.Container.Types.MessageType_Id messageTypeId_ = global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gxovnt.Messaging.Container.Types.MessageType_Id MessageTypeId {
      get { return messageTypeId_; }
      set {
        messageTypeId_ = value;
      }
    }

    /// <summary>Field number for the "Command" field.</summary>
    public const int CommandFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gxovnt.Messaging.Command Command {
      get { return msgCase_ == MsgOneofCase.Command ? (global::Gxovnt.Messaging.Command) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Command;
      }
    }

    /// <summary>Field number for the "Config" field.</summary>
    public const int ConfigFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gxovnt.Messaging.Configuration Config {
      get { return msgCase_ == MsgOneofCase.Config ? (global::Gxovnt.Messaging.Configuration) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Config;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      Command = 2,
      Config = 3,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageTypeId != other.MessageTypeId) return false;
      if (!object.Equals(Command, other.Command)) return false;
      if (!object.Equals(Config, other.Config)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageTypeId != global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command) hash ^= MessageTypeId.GetHashCode();
      if (msgCase_ == MsgOneofCase.Command) hash ^= Command.GetHashCode();
      if (msgCase_ == MsgOneofCase.Config) hash ^= Config.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageTypeId != global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageTypeId);
      }
      if (msgCase_ == MsgOneofCase.Command) {
        output.WriteRawTag(18);
        output.WriteMessage(Command);
      }
      if (msgCase_ == MsgOneofCase.Config) {
        output.WriteRawTag(26);
        output.WriteMessage(Config);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageTypeId != global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageTypeId);
      }
      if (msgCase_ == MsgOneofCase.Command) {
        output.WriteRawTag(18);
        output.WriteMessage(Command);
      }
      if (msgCase_ == MsgOneofCase.Config) {
        output.WriteRawTag(26);
        output.WriteMessage(Config);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageTypeId != global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageTypeId);
      }
      if (msgCase_ == MsgOneofCase.Command) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Command);
      }
      if (msgCase_ == MsgOneofCase.Config) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Container other) {
      if (other == null) {
        return;
      }
      if (other.MessageTypeId != global::Gxovnt.Messaging.Container.Types.MessageType_Id.Command) {
        MessageTypeId = other.MessageTypeId;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.Command:
          if (Command == null) {
            Command = new global::Gxovnt.Messaging.Command();
          }
          Command.MergeFrom(other.Command);
          break;
        case MsgOneofCase.Config:
          if (Config == null) {
            Config = new global::Gxovnt.Messaging.Configuration();
          }
          Config.MergeFrom(other.Config);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageTypeId = (global::Gxovnt.Messaging.Container.Types.MessageType_Id) input.ReadEnum();
            break;
          }
          case 18: {
            global::Gxovnt.Messaging.Command subBuilder = new global::Gxovnt.Messaging.Command();
            if (msgCase_ == MsgOneofCase.Command) {
              subBuilder.MergeFrom(Command);
            }
            input.ReadMessage(subBuilder);
            Command = subBuilder;
            break;
          }
          case 26: {
            global::Gxovnt.Messaging.Configuration subBuilder = new global::Gxovnt.Messaging.Configuration();
            if (msgCase_ == MsgOneofCase.Config) {
              subBuilder.MergeFrom(Config);
            }
            input.ReadMessage(subBuilder);
            Config = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageTypeId = (global::Gxovnt.Messaging.Container.Types.MessageType_Id) input.ReadEnum();
            break;
          }
          case 18: {
            global::Gxovnt.Messaging.Command subBuilder = new global::Gxovnt.Messaging.Command();
            if (msgCase_ == MsgOneofCase.Command) {
              subBuilder.MergeFrom(Command);
            }
            input.ReadMessage(subBuilder);
            Command = subBuilder;
            break;
          }
          case 26: {
            global::Gxovnt.Messaging.Configuration subBuilder = new global::Gxovnt.Messaging.Configuration();
            if (msgCase_ == MsgOneofCase.Config) {
              subBuilder.MergeFrom(Config);
            }
            input.ReadMessage(subBuilder);
            Config = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Container message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MessageType_Id {
        [pbr::OriginalName("COMMAND")] Command = 0,
        [pbr::OriginalName("CONFIG")] Config = 1,
        [pbr::OriginalName("Unknown")] Unknown = 99,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
