// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gxovnt.messaging.config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gxovnt.Messaging {

  /// <summary>Holder for reflection information generated from gxovnt.messaging.config.proto</summary>
  public static partial class GxovntMessagingConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for gxovnt.messaging.config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GxovntMessagingConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1neG92bnQubWVzc2FnaW5nLmNvbmZpZy5wcm90bxIQZ3hvdm50Lm1lc3Nh",
            "Z2luZyLWAwoNQ29uZmlndXJhdGlvbhJHCg9zeXN0ZW1fc2V0dGluZ3MYASAB",
            "KAsyLi5neG92bnQubWVzc2FnaW5nLkNvbmZpZ3VyYXRpb24uU3lzdGVtU2V0",
            "dGluZ3MSQwoNd2lmaV9zZXR0aW5ncxgCIAEoCzIsLmd4b3ZudC5tZXNzYWdp",
            "bmcuQ29uZmlndXJhdGlvbi5XaUZpU2V0dGluZ3MSOQoIYmxlX3RwbXMYAyAD",
            "KAsyJy5neG92bnQubWVzc2FnaW5nLkNvbmZpZ3VyYXRpb24uQkxFVFBNUxpn",
            "Cg5TeXN0ZW1TZXR0aW5ncxITCgtzeXN0ZW1fbmFtZRgBIAEoCRIRCglzeXN0",
            "ZW1faWQYAiABKAkSGAoQZmlybXdhcmVfdmVyc2lvbhgDIAEoCRITCgtzeXN0",
            "ZW1fdHlwZRgEIAEoDRouCgxXaUZpU2V0dGluZ3MSDAoEc3NpZBgBIAEoCRIQ",
            "CghwYXNzd29yZBgCIAEoCRpjCgdCTEVUUE1TEhEKCXNlbnNvcl9pZBgBIAEo",
            "CRITCgtzZW5zb3JfdHlwZRgCIAEoDRIXCg9zZW5zb3JfcG9zaXRpb24YAyAB",
            "KA0SFwoPY3VzdG9tX3Bvc2l0aW9uGAQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gxovnt.Messaging.Configuration), global::Gxovnt.Messaging.Configuration.Parser, new[]{ "SystemSettings", "WifiSettings", "BleTpms" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Gxovnt.Messaging.Configuration.Types.SystemSettings), global::Gxovnt.Messaging.Configuration.Types.SystemSettings.Parser, new[]{ "SystemName", "SystemId", "FirmwareVersion", "SystemType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gxovnt.Messaging.Configuration.Types.WiFiSettings), global::Gxovnt.Messaging.Configuration.Types.WiFiSettings.Parser, new[]{ "Ssid", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gxovnt.Messaging.Configuration.Types.BLETPMS), global::Gxovnt.Messaging.Configuration.Types.BLETPMS.Parser, new[]{ "SensorId", "SensorType", "SensorPosition", "CustomPosition" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Configuration : pb::IMessage<Configuration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Configuration> _parser = new pb::MessageParser<Configuration>(() => new Configuration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Configuration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gxovnt.Messaging.GxovntMessagingConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Configuration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Configuration(Configuration other) : this() {
      systemSettings_ = other.systemSettings_ != null ? other.systemSettings_.Clone() : null;
      wifiSettings_ = other.wifiSettings_ != null ? other.wifiSettings_.Clone() : null;
      bleTpms_ = other.bleTpms_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Configuration Clone() {
      return new Configuration(this);
    }

    /// <summary>Field number for the "system_settings" field.</summary>
    public const int SystemSettingsFieldNumber = 1;
    private global::Gxovnt.Messaging.Configuration.Types.SystemSettings systemSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gxovnt.Messaging.Configuration.Types.SystemSettings SystemSettings {
      get { return systemSettings_; }
      set {
        systemSettings_ = value;
      }
    }

    /// <summary>Field number for the "wifi_settings" field.</summary>
    public const int WifiSettingsFieldNumber = 2;
    private global::Gxovnt.Messaging.Configuration.Types.WiFiSettings wifiSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gxovnt.Messaging.Configuration.Types.WiFiSettings WifiSettings {
      get { return wifiSettings_; }
      set {
        wifiSettings_ = value;
      }
    }

    /// <summary>Field number for the "ble_tpms" field.</summary>
    public const int BleTpmsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Gxovnt.Messaging.Configuration.Types.BLETPMS> _repeated_bleTpms_codec
        = pb::FieldCodec.ForMessage(26, global::Gxovnt.Messaging.Configuration.Types.BLETPMS.Parser);
    private readonly pbc::RepeatedField<global::Gxovnt.Messaging.Configuration.Types.BLETPMS> bleTpms_ = new pbc::RepeatedField<global::Gxovnt.Messaging.Configuration.Types.BLETPMS>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gxovnt.Messaging.Configuration.Types.BLETPMS> BleTpms {
      get { return bleTpms_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Configuration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Configuration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SystemSettings, other.SystemSettings)) return false;
      if (!object.Equals(WifiSettings, other.WifiSettings)) return false;
      if(!bleTpms_.Equals(other.bleTpms_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (systemSettings_ != null) hash ^= SystemSettings.GetHashCode();
      if (wifiSettings_ != null) hash ^= WifiSettings.GetHashCode();
      hash ^= bleTpms_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (systemSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SystemSettings);
      }
      if (wifiSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(WifiSettings);
      }
      bleTpms_.WriteTo(output, _repeated_bleTpms_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (systemSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SystemSettings);
      }
      if (wifiSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(WifiSettings);
      }
      bleTpms_.WriteTo(ref output, _repeated_bleTpms_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (systemSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SystemSettings);
      }
      if (wifiSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WifiSettings);
      }
      size += bleTpms_.CalculateSize(_repeated_bleTpms_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Configuration other) {
      if (other == null) {
        return;
      }
      if (other.systemSettings_ != null) {
        if (systemSettings_ == null) {
          SystemSettings = new global::Gxovnt.Messaging.Configuration.Types.SystemSettings();
        }
        SystemSettings.MergeFrom(other.SystemSettings);
      }
      if (other.wifiSettings_ != null) {
        if (wifiSettings_ == null) {
          WifiSettings = new global::Gxovnt.Messaging.Configuration.Types.WiFiSettings();
        }
        WifiSettings.MergeFrom(other.WifiSettings);
      }
      bleTpms_.Add(other.bleTpms_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (systemSettings_ == null) {
              SystemSettings = new global::Gxovnt.Messaging.Configuration.Types.SystemSettings();
            }
            input.ReadMessage(SystemSettings);
            break;
          }
          case 18: {
            if (wifiSettings_ == null) {
              WifiSettings = new global::Gxovnt.Messaging.Configuration.Types.WiFiSettings();
            }
            input.ReadMessage(WifiSettings);
            break;
          }
          case 26: {
            bleTpms_.AddEntriesFrom(input, _repeated_bleTpms_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (systemSettings_ == null) {
              SystemSettings = new global::Gxovnt.Messaging.Configuration.Types.SystemSettings();
            }
            input.ReadMessage(SystemSettings);
            break;
          }
          case 18: {
            if (wifiSettings_ == null) {
              WifiSettings = new global::Gxovnt.Messaging.Configuration.Types.WiFiSettings();
            }
            input.ReadMessage(WifiSettings);
            break;
          }
          case 26: {
            bleTpms_.AddEntriesFrom(ref input, _repeated_bleTpms_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Configuration message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class SystemSettings : pb::IMessage<SystemSettings>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SystemSettings> _parser = new pb::MessageParser<SystemSettings>(() => new SystemSettings());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SystemSettings> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Gxovnt.Messaging.Configuration.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SystemSettings() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SystemSettings(SystemSettings other) : this() {
          systemName_ = other.systemName_;
          systemId_ = other.systemId_;
          firmwareVersion_ = other.firmwareVersion_;
          systemType_ = other.systemType_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SystemSettings Clone() {
          return new SystemSettings(this);
        }

        /// <summary>Field number for the "system_name" field.</summary>
        public const int SystemNameFieldNumber = 1;
        private string systemName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string SystemName {
          get { return systemName_; }
          set {
            systemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "system_id" field.</summary>
        public const int SystemIdFieldNumber = 2;
        private string systemId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string SystemId {
          get { return systemId_; }
          set {
            systemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "firmware_version" field.</summary>
        public const int FirmwareVersionFieldNumber = 3;
        private string firmwareVersion_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string FirmwareVersion {
          get { return firmwareVersion_; }
          set {
            firmwareVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "system_type" field.</summary>
        public const int SystemTypeFieldNumber = 4;
        private uint systemType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SystemType {
          get { return systemType_; }
          set {
            systemType_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SystemSettings);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SystemSettings other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SystemName != other.SystemName) return false;
          if (SystemId != other.SystemId) return false;
          if (FirmwareVersion != other.FirmwareVersion) return false;
          if (SystemType != other.SystemType) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (SystemName.Length != 0) hash ^= SystemName.GetHashCode();
          if (SystemId.Length != 0) hash ^= SystemId.GetHashCode();
          if (FirmwareVersion.Length != 0) hash ^= FirmwareVersion.GetHashCode();
          if (SystemType != 0) hash ^= SystemType.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (SystemName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(SystemName);
          }
          if (SystemId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(SystemId);
          }
          if (FirmwareVersion.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(FirmwareVersion);
          }
          if (SystemType != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(SystemType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (SystemName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(SystemName);
          }
          if (SystemId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(SystemId);
          }
          if (FirmwareVersion.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(FirmwareVersion);
          }
          if (SystemType != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(SystemType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (SystemName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SystemName);
          }
          if (SystemId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SystemId);
          }
          if (FirmwareVersion.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(FirmwareVersion);
          }
          if (SystemType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SystemType);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SystemSettings other) {
          if (other == null) {
            return;
          }
          if (other.SystemName.Length != 0) {
            SystemName = other.SystemName;
          }
          if (other.SystemId.Length != 0) {
            SystemId = other.SystemId;
          }
          if (other.FirmwareVersion.Length != 0) {
            FirmwareVersion = other.FirmwareVersion;
          }
          if (other.SystemType != 0) {
            SystemType = other.SystemType;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                SystemName = input.ReadString();
                break;
              }
              case 18: {
                SystemId = input.ReadString();
                break;
              }
              case 26: {
                FirmwareVersion = input.ReadString();
                break;
              }
              case 32: {
                SystemType = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                SystemName = input.ReadString();
                break;
              }
              case 18: {
                SystemId = input.ReadString();
                break;
              }
              case 26: {
                FirmwareVersion = input.ReadString();
                break;
              }
              case 32: {
                SystemType = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class WiFiSettings : pb::IMessage<WiFiSettings>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<WiFiSettings> _parser = new pb::MessageParser<WiFiSettings>(() => new WiFiSettings());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<WiFiSettings> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Gxovnt.Messaging.Configuration.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WiFiSettings() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WiFiSettings(WiFiSettings other) : this() {
          ssid_ = other.ssid_;
          password_ = other.password_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WiFiSettings Clone() {
          return new WiFiSettings(this);
        }

        /// <summary>Field number for the "ssid" field.</summary>
        public const int SsidFieldNumber = 1;
        private string ssid_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Ssid {
          get { return ssid_; }
          set {
            ssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "password" field.</summary>
        public const int PasswordFieldNumber = 2;
        private string password_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Password {
          get { return password_; }
          set {
            password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as WiFiSettings);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(WiFiSettings other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Ssid != other.Ssid) return false;
          if (Password != other.Password) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Ssid.Length != 0) hash ^= Ssid.GetHashCode();
          if (Password.Length != 0) hash ^= Password.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Ssid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Ssid);
          }
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Ssid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Ssid);
          }
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Ssid.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Ssid);
          }
          if (Password.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(WiFiSettings other) {
          if (other == null) {
            return;
          }
          if (other.Ssid.Length != 0) {
            Ssid = other.Ssid;
          }
          if (other.Password.Length != 0) {
            Password = other.Password;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Ssid = input.ReadString();
                break;
              }
              case 18: {
                Password = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Ssid = input.ReadString();
                break;
              }
              case 18: {
                Password = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class BLETPMS : pb::IMessage<BLETPMS>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<BLETPMS> _parser = new pb::MessageParser<BLETPMS>(() => new BLETPMS());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<BLETPMS> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Gxovnt.Messaging.Configuration.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BLETPMS() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BLETPMS(BLETPMS other) : this() {
          sensorId_ = other.sensorId_;
          sensorType_ = other.sensorType_;
          sensorPosition_ = other.sensorPosition_;
          customPosition_ = other.customPosition_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BLETPMS Clone() {
          return new BLETPMS(this);
        }

        /// <summary>Field number for the "sensor_id" field.</summary>
        public const int SensorIdFieldNumber = 1;
        private string sensorId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string SensorId {
          get { return sensorId_; }
          set {
            sensorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "sensor_type" field.</summary>
        public const int SensorTypeFieldNumber = 2;
        private uint sensorType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SensorType {
          get { return sensorType_; }
          set {
            sensorType_ = value;
          }
        }

        /// <summary>Field number for the "sensor_position" field.</summary>
        public const int SensorPositionFieldNumber = 3;
        private uint sensorPosition_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SensorPosition {
          get { return sensorPosition_; }
          set {
            sensorPosition_ = value;
          }
        }

        /// <summary>Field number for the "custom_position" field.</summary>
        public const int CustomPositionFieldNumber = 4;
        private string customPosition_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string CustomPosition {
          get { return customPosition_; }
          set {
            customPosition_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as BLETPMS);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(BLETPMS other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SensorId != other.SensorId) return false;
          if (SensorType != other.SensorType) return false;
          if (SensorPosition != other.SensorPosition) return false;
          if (CustomPosition != other.CustomPosition) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (SensorId.Length != 0) hash ^= SensorId.GetHashCode();
          if (SensorType != 0) hash ^= SensorType.GetHashCode();
          if (SensorPosition != 0) hash ^= SensorPosition.GetHashCode();
          if (CustomPosition.Length != 0) hash ^= CustomPosition.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (SensorId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(SensorId);
          }
          if (SensorType != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(SensorType);
          }
          if (SensorPosition != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(SensorPosition);
          }
          if (CustomPosition.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(CustomPosition);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (SensorId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(SensorId);
          }
          if (SensorType != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(SensorType);
          }
          if (SensorPosition != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(SensorPosition);
          }
          if (CustomPosition.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(CustomPosition);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (SensorId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SensorId);
          }
          if (SensorType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SensorType);
          }
          if (SensorPosition != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SensorPosition);
          }
          if (CustomPosition.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomPosition);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(BLETPMS other) {
          if (other == null) {
            return;
          }
          if (other.SensorId.Length != 0) {
            SensorId = other.SensorId;
          }
          if (other.SensorType != 0) {
            SensorType = other.SensorType;
          }
          if (other.SensorPosition != 0) {
            SensorPosition = other.SensorPosition;
          }
          if (other.CustomPosition.Length != 0) {
            CustomPosition = other.CustomPosition;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                SensorId = input.ReadString();
                break;
              }
              case 16: {
                SensorType = input.ReadUInt32();
                break;
              }
              case 24: {
                SensorPosition = input.ReadUInt32();
                break;
              }
              case 34: {
                CustomPosition = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                SensorId = input.ReadString();
                break;
              }
              case 16: {
                SensorType = input.ReadUInt32();
                break;
              }
              case 24: {
                SensorPosition = input.ReadUInt32();
                break;
              }
              case 34: {
                CustomPosition = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
