/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_CONTAINER_PB_H_INCLUDED
#define PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_CONTAINER_PB_H_INCLUDED
#include "pb.h"
#include "gxovnt.messaging.command.pb.h"
#include "gxovnt.messaging.config.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _gxovnt_messaging_Container_MessageType_Id {
    gxovnt_messaging_Container_MessageType_Id_ClearConfig = 0,
    gxovnt_messaging_Container_MessageType_Id_SaveConfig = 1,
    gxovnt_messaging_Container_MessageType_Id_SetSystemName = 2,
    gxovnt_messaging_Container_MessageType_Id_GetSystemName = 3,
    gxovnt_messaging_Container_MessageType_Id_SetSystemType = 4,
    gxovnt_messaging_Container_MessageType_Id_GetSystemType = 5,
    gxovnt_messaging_Container_MessageType_Id_SetWiFiSSID = 6,
    gxovnt_messaging_Container_MessageType_Id_GetWiFiSSID = 7,
    gxovnt_messaging_Container_MessageType_Id_SetWiFiPassword = 8,
    gxovnt_messaging_Container_MessageType_Id_GetWiFiPassword = 9
} gxovnt_messaging_Container_MessageType_Id;

/* Struct definitions */
typedef struct _gxovnt_messaging_Container {
    gxovnt_messaging_Container_MessageType_Id messageTypeId;
    pb_size_t which_msg;
    union {
        pb_callback_t TextValue;
        int32_t IntValue;
    } msg;
} gxovnt_messaging_Container;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _gxovnt_messaging_Container_MessageType_Id_MIN gxovnt_messaging_Container_MessageType_Id_ClearConfig
#define _gxovnt_messaging_Container_MessageType_Id_MAX gxovnt_messaging_Container_MessageType_Id_GetWiFiPassword
#define _gxovnt_messaging_Container_MessageType_Id_ARRAYSIZE ((gxovnt_messaging_Container_MessageType_Id)(gxovnt_messaging_Container_MessageType_Id_GetWiFiPassword+1))

#define gxovnt_messaging_Container_messageTypeId_ENUMTYPE gxovnt_messaging_Container_MessageType_Id


/* Initializer values for message structs */
#define gxovnt_messaging_Container_init_default  {_gxovnt_messaging_Container_MessageType_Id_MIN, 0, {{{NULL}, NULL}}}
#define gxovnt_messaging_Container_init_zero     {_gxovnt_messaging_Container_MessageType_Id_MIN, 0, {{{NULL}, NULL}}}

/* Field tags (for use in manual encoding/decoding) */
#define gxovnt_messaging_Container_messageTypeId_tag 1
#define gxovnt_messaging_Container_TextValue_tag 2
#define gxovnt_messaging_Container_IntValue_tag  3

/* Struct field encoding specification for nanopb */
#define gxovnt_messaging_Container_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    messageTypeId,     1) \
X(a, CALLBACK, ONEOF,    STRING,   (msg,TextValue,msg.TextValue),   2) \
X(a, STATIC,   ONEOF,    INT32,    (msg,IntValue,msg.IntValue),   3)
#define gxovnt_messaging_Container_CALLBACK pb_default_field_callback
#define gxovnt_messaging_Container_DEFAULT NULL

extern const pb_msgdesc_t gxovnt_messaging_Container_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gxovnt_messaging_Container_fields &gxovnt_messaging_Container_msg

/* Maximum encoded size of messages (where known) */
/* gxovnt_messaging_Container_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
