/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GXOVNT_CONFIG_PB_H_INCLUDED
#define PB_GXOVNT_CONFIG_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GXOVnTConfig_SYSTEM_SETTINGS {
    pb_callback_t _system_name;
    pb_callback_t _system_id;
    pb_callback_t _firmware_version;
    uint32_t _system_type;
} GXOVnTConfig_SYSTEM_SETTINGS;

typedef struct _GXOVnTConfig_WIFISETTINGS {
    pb_callback_t _s_s_i_d;
    pb_callback_t _password;
} GXOVnTConfig_WIFISETTINGS;

typedef struct _GXOVnTConfig {
    bool has_system_settings;
    GXOVnTConfig_SYSTEM_SETTINGS system_settings;
    bool has_wifi_settings;
    GXOVnTConfig_WIFISETTINGS wifi_settings;
    pb_callback_t ble_tpms;
} GXOVnTConfig;

typedef struct _GXOVnTConfig_BLE_TPMS {
    pb_callback_t _sensor_id;
    uint32_t _sensor_type;
    uint32_t _sensor_position;
    pb_callback_t _custom_position;
} GXOVnTConfig_BLE_TPMS;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GXOVnTConfig_init_default                {false, GXOVnTConfig_SYSTEM_SETTINGS_init_default, false, GXOVnTConfig_WIFISETTINGS_init_default, {{NULL}, NULL}}
#define GXOVnTConfig_SYSTEM_SETTINGS_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define GXOVnTConfig_WIFISETTINGS_init_default   {{{NULL}, NULL}, {{NULL}, NULL}}
#define GXOVnTConfig_BLE_TPMS_init_default       {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define GXOVnTConfig_init_zero                   {false, GXOVnTConfig_SYSTEM_SETTINGS_init_zero, false, GXOVnTConfig_WIFISETTINGS_init_zero, {{NULL}, NULL}}
#define GXOVnTConfig_SYSTEM_SETTINGS_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define GXOVnTConfig_WIFISETTINGS_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}}
#define GXOVnTConfig_BLE_TPMS_init_zero          {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GXOVnTConfig_SYSTEM_SETTINGS__system_name_tag 1
#define GXOVnTConfig_SYSTEM_SETTINGS__system_id_tag 2
#define GXOVnTConfig_SYSTEM_SETTINGS__firmware_version_tag 3
#define GXOVnTConfig_SYSTEM_SETTINGS__system_type_tag 4
#define GXOVnTConfig_WIFISETTINGS__s_s_i_d_tag   1
#define GXOVnTConfig_WIFISETTINGS__password_tag  2
#define GXOVnTConfig_system_settings_tag         1
#define GXOVnTConfig_wifi_settings_tag           2
#define GXOVnTConfig_ble_tpms_tag                3
#define GXOVnTConfig_BLE_TPMS__sensor_id_tag     1
#define GXOVnTConfig_BLE_TPMS__sensor_type_tag   2
#define GXOVnTConfig_BLE_TPMS__sensor_position_tag 3
#define GXOVnTConfig_BLE_TPMS__custom_position_tag 4

/* Struct field encoding specification for nanopb */
#define GXOVnTConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_settings,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_settings,     2) \
X(a, CALLBACK, REPEATED, MESSAGE,  ble_tpms,          3)
#define GXOVnTConfig_CALLBACK pb_default_field_callback
#define GXOVnTConfig_DEFAULT NULL
#define GXOVnTConfig_system_settings_MSGTYPE GXOVnTConfig_SYSTEM_SETTINGS
#define GXOVnTConfig_wifi_settings_MSGTYPE GXOVnTConfig_WIFISETTINGS
#define GXOVnTConfig_ble_tpms_MSGTYPE GXOVnTConfig_BLE_TPMS

#define GXOVnTConfig_SYSTEM_SETTINGS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   _system_name,      1) \
X(a, CALLBACK, SINGULAR, STRING,   _system_id,        2) \
X(a, CALLBACK, SINGULAR, STRING,   _firmware_version,   3) \
X(a, STATIC,   SINGULAR, UINT32,   _system_type,      4)
#define GXOVnTConfig_SYSTEM_SETTINGS_CALLBACK pb_default_field_callback
#define GXOVnTConfig_SYSTEM_SETTINGS_DEFAULT NULL

#define GXOVnTConfig_WIFISETTINGS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   _s_s_i_d,          1) \
X(a, CALLBACK, SINGULAR, STRING,   _password,         2)
#define GXOVnTConfig_WIFISETTINGS_CALLBACK pb_default_field_callback
#define GXOVnTConfig_WIFISETTINGS_DEFAULT NULL

#define GXOVnTConfig_BLE_TPMS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   _sensor_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   _sensor_type,      2) \
X(a, STATIC,   SINGULAR, UINT32,   _sensor_position,   3) \
X(a, CALLBACK, SINGULAR, STRING,   _custom_position,   4)
#define GXOVnTConfig_BLE_TPMS_CALLBACK pb_default_field_callback
#define GXOVnTConfig_BLE_TPMS_DEFAULT NULL

extern const pb_msgdesc_t GXOVnTConfig_msg;
extern const pb_msgdesc_t GXOVnTConfig_SYSTEM_SETTINGS_msg;
extern const pb_msgdesc_t GXOVnTConfig_WIFISETTINGS_msg;
extern const pb_msgdesc_t GXOVnTConfig_BLE_TPMS_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GXOVnTConfig_fields &GXOVnTConfig_msg
#define GXOVnTConfig_SYSTEM_SETTINGS_fields &GXOVnTConfig_SYSTEM_SETTINGS_msg
#define GXOVnTConfig_WIFISETTINGS_fields &GXOVnTConfig_WIFISETTINGS_msg
#define GXOVnTConfig_BLE_TPMS_fields &GXOVnTConfig_BLE_TPMS_msg

/* Maximum encoded size of messages (where known) */
/* GXOVnTConfig_size depends on runtime parameters */
/* GXOVnTConfig_SYSTEM_SETTINGS_size depends on runtime parameters */
/* GXOVnTConfig_WIFISETTINGS_size depends on runtime parameters */
/* GXOVnTConfig_BLE_TPMS_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
