/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GXOVNT_COMMAND_PB_H_INCLUDED
#define PB_GXOVNT_COMMAND_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _GXOVnTCommand_COMMAND_ID {
    GXOVnTCommand_COMMAND_ID_GET_CONFIG = 0,
    GXOVnTCommand_COMMAND_ID_UPDATE_FIRMWARE = 1,
    GXOVnTCommand_COMMAND_ID_NOT_SET = 99
} GXOVnTCommand_COMMAND_ID;

/* Struct definitions */
typedef struct _GXOVnTCommand {
    GXOVnTCommand_COMMAND_ID commandId;
} GXOVnTCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _GXOVnTCommand_COMMAND_ID_MIN GXOVnTCommand_COMMAND_ID_GET_CONFIG
#define _GXOVnTCommand_COMMAND_ID_MAX GXOVnTCommand_COMMAND_ID_NOT_SET
#define _GXOVnTCommand_COMMAND_ID_ARRAYSIZE ((GXOVnTCommand_COMMAND_ID)(GXOVnTCommand_COMMAND_ID_NOT_SET+1))

#define GXOVnTCommand_commandId_ENUMTYPE GXOVnTCommand_COMMAND_ID


/* Initializer values for message structs */
#define GXOVnTCommand_init_default               {_GXOVnTCommand_COMMAND_ID_MIN}
#define GXOVnTCommand_init_zero                  {_GXOVnTCommand_COMMAND_ID_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define GXOVnTCommand_commandId_tag              99

/* Struct field encoding specification for nanopb */
#define GXOVnTCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    commandId,        99)
#define GXOVnTCommand_CALLBACK NULL
#define GXOVnTCommand_DEFAULT NULL

extern const pb_msgdesc_t GXOVnTCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GXOVnTCommand_fields &GXOVnTCommand_msg

/* Maximum encoded size of messages (where known) */
#define GXOVNT_COMMAND_PB_H_MAX_SIZE             GXOVnTCommand_size
#define GXOVnTCommand_size                       3

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
