/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_CONFIG_PB_H_INCLUDED
#define PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_CONFIG_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _gxovnt_messaging_Configuration_SystemSettings {
    pb_callback_t system_name;
    pb_callback_t system_id;
    pb_callback_t firmware_version;
    uint32_t system_type;
} gxovnt_messaging_Configuration_SystemSettings;

typedef struct _gxovnt_messaging_Configuration_WiFiSettings {
    pb_callback_t ssid;
    pb_callback_t password;
} gxovnt_messaging_Configuration_WiFiSettings;

typedef struct _gxovnt_messaging_Configuration {
    bool has_system_settings;
    gxovnt_messaging_Configuration_SystemSettings system_settings;
    bool has_wifi_settings;
    gxovnt_messaging_Configuration_WiFiSettings wifi_settings;
    pb_callback_t ble_tpms;
} gxovnt_messaging_Configuration;

typedef struct _gxovnt_messaging_Configuration_BLETPMS {
    pb_callback_t sensor_id;
    uint32_t sensor_type;
    uint32_t sensor_position;
    pb_callback_t custom_position;
} gxovnt_messaging_Configuration_BLETPMS;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define gxovnt_messaging_Configuration_init_default {false, gxovnt_messaging_Configuration_SystemSettings_init_default, false, gxovnt_messaging_Configuration_WiFiSettings_init_default, {{NULL}, NULL}}
#define gxovnt_messaging_Configuration_SystemSettings_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define gxovnt_messaging_Configuration_WiFiSettings_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define gxovnt_messaging_Configuration_BLETPMS_init_default {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define gxovnt_messaging_Configuration_init_zero {false, gxovnt_messaging_Configuration_SystemSettings_init_zero, false, gxovnt_messaging_Configuration_WiFiSettings_init_zero, {{NULL}, NULL}}
#define gxovnt_messaging_Configuration_SystemSettings_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define gxovnt_messaging_Configuration_WiFiSettings_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define gxovnt_messaging_Configuration_BLETPMS_init_zero {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define gxovnt_messaging_Configuration_SystemSettings_system_name_tag 1
#define gxovnt_messaging_Configuration_SystemSettings_system_id_tag 2
#define gxovnt_messaging_Configuration_SystemSettings_firmware_version_tag 3
#define gxovnt_messaging_Configuration_SystemSettings_system_type_tag 4
#define gxovnt_messaging_Configuration_WiFiSettings_ssid_tag 1
#define gxovnt_messaging_Configuration_WiFiSettings_password_tag 2
#define gxovnt_messaging_Configuration_system_settings_tag 1
#define gxovnt_messaging_Configuration_wifi_settings_tag 2
#define gxovnt_messaging_Configuration_ble_tpms_tag 3
#define gxovnt_messaging_Configuration_BLETPMS_sensor_id_tag 1
#define gxovnt_messaging_Configuration_BLETPMS_sensor_type_tag 2
#define gxovnt_messaging_Configuration_BLETPMS_sensor_position_tag 3
#define gxovnt_messaging_Configuration_BLETPMS_custom_position_tag 4

/* Struct field encoding specification for nanopb */
#define gxovnt_messaging_Configuration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_settings,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_settings,     2) \
X(a, CALLBACK, REPEATED, MESSAGE,  ble_tpms,          3)
#define gxovnt_messaging_Configuration_CALLBACK pb_default_field_callback
#define gxovnt_messaging_Configuration_DEFAULT NULL
#define gxovnt_messaging_Configuration_system_settings_MSGTYPE gxovnt_messaging_Configuration_SystemSettings
#define gxovnt_messaging_Configuration_wifi_settings_MSGTYPE gxovnt_messaging_Configuration_WiFiSettings
#define gxovnt_messaging_Configuration_ble_tpms_MSGTYPE gxovnt_messaging_Configuration_BLETPMS

#define gxovnt_messaging_Configuration_SystemSettings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   system_name,       1) \
X(a, CALLBACK, SINGULAR, STRING,   system_id,         2) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_version,   3) \
X(a, STATIC,   SINGULAR, UINT32,   system_type,       4)
#define gxovnt_messaging_Configuration_SystemSettings_CALLBACK pb_default_field_callback
#define gxovnt_messaging_Configuration_SystemSettings_DEFAULT NULL

#define gxovnt_messaging_Configuration_WiFiSettings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,              1) \
X(a, CALLBACK, SINGULAR, STRING,   password,          2)
#define gxovnt_messaging_Configuration_WiFiSettings_CALLBACK pb_default_field_callback
#define gxovnt_messaging_Configuration_WiFiSettings_DEFAULT NULL

#define gxovnt_messaging_Configuration_BLETPMS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_type,       2) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_position,   3) \
X(a, CALLBACK, SINGULAR, STRING,   custom_position,   4)
#define gxovnt_messaging_Configuration_BLETPMS_CALLBACK pb_default_field_callback
#define gxovnt_messaging_Configuration_BLETPMS_DEFAULT NULL

extern const pb_msgdesc_t gxovnt_messaging_Configuration_msg;
extern const pb_msgdesc_t gxovnt_messaging_Configuration_SystemSettings_msg;
extern const pb_msgdesc_t gxovnt_messaging_Configuration_WiFiSettings_msg;
extern const pb_msgdesc_t gxovnt_messaging_Configuration_BLETPMS_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gxovnt_messaging_Configuration_fields &gxovnt_messaging_Configuration_msg
#define gxovnt_messaging_Configuration_SystemSettings_fields &gxovnt_messaging_Configuration_SystemSettings_msg
#define gxovnt_messaging_Configuration_WiFiSettings_fields &gxovnt_messaging_Configuration_WiFiSettings_msg
#define gxovnt_messaging_Configuration_BLETPMS_fields &gxovnt_messaging_Configuration_BLETPMS_msg

/* Maximum encoded size of messages (where known) */
/* gxovnt_messaging_Configuration_size depends on runtime parameters */
/* gxovnt_messaging_Configuration_SystemSettings_size depends on runtime parameters */
/* gxovnt_messaging_Configuration_WiFiSettings_size depends on runtime parameters */
/* gxovnt_messaging_Configuration_BLETPMS_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
