/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_COMMAND_PB_H_INCLUDED
#define PB_GXOVNT_MESSAGING_GXOVNT_MESSAGING_COMMAND_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _gxovnt_messaging_Command_Command_Id {
    gxovnt_messaging_Command_Command_Id_GET_CONFIG = 0,
    gxovnt_messaging_Command_Command_Id_UPDATE_FIRMWARE = 1,
    gxovnt_messaging_Command_Command_Id_NOT_SET = 99
} gxovnt_messaging_Command_Command_Id;

/* Struct definitions */
typedef struct _gxovnt_messaging_Command {
    gxovnt_messaging_Command_Command_Id commandId;
} gxovnt_messaging_Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _gxovnt_messaging_Command_Command_Id_MIN gxovnt_messaging_Command_Command_Id_GET_CONFIG
#define _gxovnt_messaging_Command_Command_Id_MAX gxovnt_messaging_Command_Command_Id_NOT_SET
#define _gxovnt_messaging_Command_Command_Id_ARRAYSIZE ((gxovnt_messaging_Command_Command_Id)(gxovnt_messaging_Command_Command_Id_NOT_SET+1))

#define gxovnt_messaging_Command_commandId_ENUMTYPE gxovnt_messaging_Command_Command_Id


/* Initializer values for message structs */
#define gxovnt_messaging_Command_init_default    {_gxovnt_messaging_Command_Command_Id_MIN}
#define gxovnt_messaging_Command_init_zero       {_gxovnt_messaging_Command_Command_Id_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define gxovnt_messaging_Command_commandId_tag   1

/* Struct field encoding specification for nanopb */
#define gxovnt_messaging_Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    commandId,         1)
#define gxovnt_messaging_Command_CALLBACK NULL
#define gxovnt_messaging_Command_DEFAULT NULL

extern const pb_msgdesc_t gxovnt_messaging_Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gxovnt_messaging_Command_fields &gxovnt_messaging_Command_msg

/* Maximum encoded size of messages (where known) */
#define GXOVNT_MESSAGING_GXOVNT_MESSAGING_COMMAND_PB_H_MAX_SIZE gxovnt_messaging_Command_size
#define gxovnt_messaging_Command_size            2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
