/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_MSG_GXOVNT_CONFIG_PB_H_INCLUDED
#define PB_MSG_GXOVNT_CONFIG_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings {
    pb_callback_t system_name;
    pb_callback_t system_id;
    pb_callback_t firmware_version;
    uint32_t system_type;
} MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings;

typedef struct _MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings {
    pb_callback_t ssid;
    pb_callback_t password;
} MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings;

typedef struct _MSG_GXOVnT_Config {
    bool has_system_settings;
    MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings system_settings;
    bool has_wifi_settings;
    MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings wifi_settings;
    pb_callback_t ble_tpms;
} MSG_GXOVnT_Config;

typedef struct _MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS {
    pb_callback_t sensor_id;
    uint32_t sensor_type;
    uint32_t sensor_position;
    pb_callback_t custom_position;
} MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MSG_GXOVnT_Config_init_default           {false, MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_init_default, false, MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_init_default, {{NULL}, NULL}}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_init_default {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define MSG_GXOVnT_Config_init_zero              {false, MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_init_zero, false, MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_init_zero, {{NULL}, NULL}}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_init_zero {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_system_name_tag 1
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_system_id_tag 2
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_firmware_version_tag 3
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_system_type_tag 4
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_ssid_tag 1
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_password_tag 2
#define MSG_GXOVnT_Config_system_settings_tag    1
#define MSG_GXOVnT_Config_wifi_settings_tag      2
#define MSG_GXOVnT_Config_ble_tpms_tag           3
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_sensor_id_tag 1
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_sensor_type_tag 2
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_sensor_position_tag 3
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_custom_position_tag 4

/* Struct field encoding specification for nanopb */
#define MSG_GXOVnT_Config_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_settings,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_settings,     2) \
X(a, CALLBACK, REPEATED, MESSAGE,  ble_tpms,          3)
#define MSG_GXOVnT_Config_CALLBACK pb_default_field_callback
#define MSG_GXOVnT_Config_DEFAULT NULL
#define MSG_GXOVnT_Config_system_settings_MSGTYPE MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings
#define MSG_GXOVnT_Config_wifi_settings_MSGTYPE MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings
#define MSG_GXOVnT_Config_ble_tpms_MSGTYPE MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS

#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   system_name,       1) \
X(a, CALLBACK, SINGULAR, STRING,   system_id,         2) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_version,   3) \
X(a, STATIC,   SINGULAR, UINT32,   system_type,       4)
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_CALLBACK pb_default_field_callback
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_DEFAULT NULL

#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,              1) \
X(a, CALLBACK, SINGULAR, STRING,   password,          2)
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_CALLBACK pb_default_field_callback
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_DEFAULT NULL

#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_type,       2) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_position,   3) \
X(a, CALLBACK, SINGULAR, STRING,   custom_position,   4)
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_CALLBACK pb_default_field_callback
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_DEFAULT NULL

extern const pb_msgdesc_t MSG_GXOVnT_Config_msg;
extern const pb_msgdesc_t MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_msg;
extern const pb_msgdesc_t MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_msg;
extern const pb_msgdesc_t MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MSG_GXOVnT_Config_fields &MSG_GXOVnT_Config_msg
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_fields &MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_msg
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_fields &MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_msg
#define MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_fields &MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_msg

/* Maximum encoded size of messages (where known) */
/* MSG_GXOVnT_Config_size depends on runtime parameters */
/* MSG_GXOVnT_Config_MSG_GXOVnT_Config_System_Settings_size depends on runtime parameters */
/* MSG_GXOVnT_Config_MSG_GXOVnT_Config_WiFi_Settings_size depends on runtime parameters */
/* MSG_GXOVnT_Config_MSG_GXOVnT_Config_BLE_TPMS_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
